module.exports = [
    '(s. str.)',
    'COMB. NOV',
    'COMB. NOV.',
    'Comb. nov',
    'Comb. nov.',
    'GEN. NOV.',
    'Gen. Nov.',
    'N. GEN.',
    'N.COMB.',
    'NEW COMBINATION',
    'NEW GENUS',
    'NEW SP.',
    'NEW SPECIES',
    'NEW SSP.',
    'NEW STATUS',
    'New Combination',
    'New Genus',
    'New Species',
    'New Status',
    'New Subspecies',
    'New combination',
    'New genus',
    'New species',
    'New status',
    'STAT. NOV.',
    'STAT. REV.',
    'Synonym',
    'Transf. from Amaurobius',
    'com. nov.',
    'comB. nov.',
    'comb n.',
    'comb nov.',
    'comb.',
    'comb. n',
    'comb. n.',
    'comb. nov',
    'comb. nov.',
    'comb.n.',
    'comb.nov.',
    'fam. nov.',
    'gen nov. et sp. nov.',
    'gen. et comb. nov.',
    'gen. et sp. nov.',
    'gen. n',
    'gen. n.',
    'gen. nov',
    'gen. nov.',
    'gen. nov. et sp. nov.',
    'gen. nov., sp. nov.',
    'gen.n.',
    'gen.nov.',
    'genus nov.',
    'hybr. nov.',
    'incertae sedis',
    'n . comb.',
    'n . sp .',
    'n . sp.',
    'n sp.',
    'n. Comb.',
    'n. comb',
    'n. comb.',
    'n. g.',
    'n. g., n. sp.',
    'n. gen.',
    'n. gen., n. sp.',
    'n. sp .',
    'n. sp.',
    'n. ssp.',
    'n. st.',
    'n. stat.',
    'n. stat., n. comb.',
    'n. subg.',
    'n. subgen.',
    'n. subgenus',
    'n. subsp.',
    'n. v.',
    'n. var.',
    'n.comb',
    'n.comb.',
    'n.gen.',
    'n.sp.',
    'n.ssp.',
    'n.stat.',
    'new',
    'new comb',
    'new comb.',
    'new combination',
    'new gen.',
    'new genus',
    'new replacement name',
    'new sPecies',
    'new sp.',
    'new speCies',
    'new spec.',
    'new specIes',
    'new species',
    'new status',
    'new subgenus',
    'new subspecies',
    'new synonym',
    'nom. n.',
    'nom. nov.',
    'nom.nov.',
    'nomina dubia',
    'nov. comb.',
    'nov. gen.',
    'nov. sp.',
    'nov. spec.',
    'nov. ssp.',
    'nov. st.',
    'nov. subgen.',
    'nov. var.',
    'nov.sp.',
    's. str.',
    's.l.',
    's.s.',
    'sP. nov.',
    'sensu lato',
    'sensu stricto',
    'sp . n .',
    'sp . nov',
    'sp . nov .',
    'sp . nov.',
    'sp .n.',
    'sp .nov.',
    'sp.',
    'sp. and subsp. nov.',
    'sp. n',
    'sp. n.',
    'sp. noV.',
    'sp. nov',
    'sp. nov.',
    'sp.n',
    'sp.n.',
    'sp.nov',
    'sp.nov.',
    'spec.',
    'spec. n.',
    'spec. nov',
    'spec. nov.',
    'spec. nova',
    'spec.nov.',
    'species nov.',
    'ssp. n.',
    'ssp. nov',
    'ssp. nov.',
    'ssp.n.',
    'stat rev.',
    'stat. nov',
    'stat. nov.',
    'stat. rev.',
    'stat.nov.',
    'stat.rev.',
    'subfam. nov.',
    'subgen. n.',
    'subgen. nov.',
    'subsp. n.',
    'subsp. nov',
    'subsp. nov.',
    'subspec. nov.',
    'subspecies nov.',
    'syn. n.',
    'syn. nov.',
    'syn.n.',
    'synonym',
    'tranf. to Araniella',
    'tranf. to Bianor',
    'tranf. to Borboropactus',
    'tranf. to Diaea',
    'tranf. to Drassodes',
    'tranf. to Henriksenia',
    'tranf. to Lysteles',
    'tranf. to Massuria',
    'transf. from Agroeca',
    'transf. from Alaeho',
    'transf. from Phrurolithus',
    'transf. from Scotinella',
    'transf. to Corinnoma'
];